CI/CD - build libjxl as static lib

diff --git a/.github/workflows/build_sview_android_ffmpeg.yml b/.github/workflows/build_sview_android_ffmpeg.yml
--- a/.github/workflows/build_sview_android_ffmpeg.yml
+++ b/.github/workflows/build_sview_android_ffmpeg.yml
@@ -19,7 +19,7 @@ env:
   LIBJXL_REF:   'v0.11.1'
   #MBEDTLS_REF:  'v4.0.0' untested
   MBEDTLS_REF:  'v3.6.5'
-  CACHE_REV:    'cache1'
+  CACHE_REV:    'cache4'
 
 jobs:
   build-mbedtls:
@@ -95,6 +95,12 @@ jobs:
         ref: ${{ env.LIBJXL_REF }}
         fetch-depth: 1
         submodules: 'true'
+    - name: Clone sView Tree
+      if: steps.cache.outputs.cache-hit != 'true'
+      uses: actions/checkout@v6
+      with:
+        path: sview.git
+        fetch-depth: 1
     - name: Install Dependencies
       if: steps.cache.outputs.cache-hit != 'true'
       run: |
@@ -114,12 +120,15 @@ jobs:
           set(JPEGXL_ENABLE_PLUGINS   OFF CACHE BOOL "")
           set(JPEGXL_ENABLE_TOOLS     OFF CACHE BOOL "")
           set(JPEGXL_ENABLE_DEVTOOLS  OFF CACHE BOOL "")
+          set(JPEGXL_ENABLE_SJPEG     OFF CACHE BOOL "")
+          set(JPEGXL_ENABLE_OPENEXR   OFF CACHE BOOL "")
           set(JPEGXL_TEST_TOOLS       OFF CACHE BOOL "")
           set(BUILD_TESTING           OFF CACHE BOOL "")
+          set(BUILD_SHARED_LIBS       OFF CACHE BOOL "")
           ${{ env.TOOLCHAIN_TEXT }}
           # workaround bogus 'third_party/sjpeg/cmake/cpu.cmake'
-          set(SJPEG_ANDROID_NDK_PATH "$ENV{ANDROID_NDK}" CACHE PATH "")
-          set(ANDROID_ABI "${CMAKE_ANDROID_ARCH_ABI}"  CACHE STRING "")
+          #set(SJPEG_ANDROID_NDK_PATH "$ENV{ANDROID_NDK}" CACHE PATH "")
+          #set(ANDROID_ABI "${CMAKE_ANDROID_ARCH_ABI}"  CACHE STRING "")
           set(CMAKE_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_DIR}/libjxl-install" CACHE PATH "")
       run: |
         echo "ANDROID_NDK=$ANDROID_NDK"
@@ -133,8 +142,15 @@ jobs:
       if: steps.cache.outputs.cache-hit != 'true'
       run: |
         cmake --install ./libjxl-make --prefix ./libjxl-install
-        cp -f "./libjxl.git/LICENSE"   "./libjxl-install/"
-        cp -f "./libjxl.git/README.md" "./libjxl-install/"
+    - name: Post install
+      if: steps.cache.outputs.cache-hit != 'true'
+      run: |
+        cp -f ./libjxl.git/LICENSE   ./libjxl-install/
+        cp -f ./libjxl.git/README.md ./libjxl-install/
+        # check shared library
+        #otool -l ./libjxl-install/lib/libjxl.dylib
+        # fix broken dependencies for static build (marked as 'private')
+        patch -d ./libjxl-install/lib -s -p0 < ./sview.git/3rdparty/FFmpeg/libjxl-static/libjxl-pkgconfig-static-android.patch
     - name: Upload build
       uses: actions/upload-artifact@v4
       with:
@@ -279,6 +295,7 @@ jobs:
         cmake --install ./openjpeg-make --prefix ./openjpeg-install
     - name: Configure FFmpeg
       if: steps.cache.outputs.cache-hit != 'true'
+      id: configure
       run: |
         # --enable-mbedtls cannot be found by ffmpeg configure via pkg-config,
         # so we pass -I and -L flags directly via --extra-cflags and --extra-ldflags.
@@ -287,10 +304,9 @@ jobs:
         export PKG_CONFIG_PATH=$PWD/dav1d-install/lib/pkgconfig:$PWD/openjpeg-install/lib/pkgconfig:$PWD/libjxl-install/lib/pkgconfig:$PWD/mbedtls-install/lib/pkgconfig
         aBuildRoot=$PWD
         aToolchainRoot="${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64"
-        # redirect error state from tee
         set -o pipefail
         pushd ./ffmpeg.git
-        ./configure \
+        if ./configure \
           --prefix="$aBuildRoot/ffmpeg-install" \
           --enable-cross-compile --target-os=android --pkg-config=pkg-config \
           --cross-prefix="${aToolchainRoot}/bin/aarch64-linux-android21-" \
@@ -306,10 +322,29 @@ jobs:
           --enable-runtime-cpudetect \
           --enable-libdav1d --enable-libjxl \
           --enable-jni --enable-mediacodec --enable-mbedtls \
-          --extra-cflags="-march=armv8-a -I$aBuildRoot/dav1d-install/include -I$aBuildRoot/openjpeg-install/include -I$aBuildRoot/libjxl-install/include -I$aBuildRoot/mbedtls-install/include" \
-          --extra-ldflags="-L$aBuildRoot/dav1d-install/lib -L$aBuildRoot/openjpeg-install/lib -L$aBuildRoot/libjxl-install/lib -L$aBuildRoot/mbedtls-install/lib" \
-          2>&1 | tee ../ffmpeg-config.log
+          --extra-cflags="-march=armv8-a -I$aBuildRoot/dav1d-install/include -I$aBuildRoot/openjpeg-install/include -I$aBuildRoot/mbedtls-install/include" \
+          --extra-ldflags="-L$aBuildRoot/dav1d-install/lib -L$aBuildRoot/openjpeg-install/lib -L$aBuildRoot/mbedtls-install/lib" \
+            2>&1 | tee ../ffmpeg-config.log; then
+          echo "status=true" >> $GITHUB_OUTPUT
+        else
+          echo "status=false" >> $GITHUB_OUTPUT
+        fi
         popd
+    - name: Upload FFmpeg configure log
+      if: steps.cache.outputs.cache-hit != 'true'
+      uses: actions/upload-artifact@v4
+      with:
+        name: ffmpeg-${{ env.SYSTEM }}-${{ env.ARCH }}-config.log
+        path: ffmpeg.git/ffbuild/config.log
+        if-no-files-found: error
+        retention-days: 1
+    - name: Check FFmpeg configure status
+      if: steps.cache.outputs.cache-hit != 'true'
+      run: |
+        if [ "${{ steps.configure.outputs.status }}" != "true" ]; then
+          echo "Error: configuration failed, check logs"
+          exit 1
+        fi
     - name: Build FFmpeg
       if: steps.cache.outputs.cache-hit != 'true'
       run: |
@@ -323,6 +358,9 @@ jobs:
         pushd ./ffmpeg.git
         make install
         popd
+    - name: Post Install FFmpeg
+      if: steps.cache.outputs.cache-hit != 'true'
+      run: |
         cp -f ./ffmpeg-config.log           ./ffmpeg-install/
         cp -f ./ffmpeg.git/Changelog        ./ffmpeg-install/
         cp -f ./ffmpeg.git/README.md        ./ffmpeg-install/
@@ -330,7 +368,7 @@ jobs:
         cp -f ./ffmpeg.git/COPYING.LGPLv2.1 ./ffmpeg-install/
         cp -f ./ffmpeg.git/COPYING.LGPLv3   ./ffmpeg-install/
         # copy dependencies
-        cp -f ./libjxl-install/lib/*.so ./ffmpeg-install/lib/
+        #cp -f ./libjxl-install/lib/*.so ./ffmpeg-install/lib/
     - name: Upload build
       uses: actions/upload-artifact@v4
       with:
diff --git a/.github/workflows/build_sview_macos_ffmpeg.yml b/.github/workflows/build_sview_macos_ffmpeg.yml
--- a/.github/workflows/build_sview_macos_ffmpeg.yml
+++ b/.github/workflows/build_sview_macos_ffmpeg.yml
@@ -16,7 +16,7 @@ env:
   OPENJPEG_REF: 'v2.5.4'
   DAV1_REF:     '1.5.3'
   LIBJXL_REF:   'v0.11.1'
-  CACHE_REV:    'cache3'
+  CACHE_REV:    'cache10'
 
 jobs:
   build-libjxl:
@@ -36,6 +36,12 @@ jobs:
         ref: ${{ env.LIBJXL_REF }}
         fetch-depth: 1
         submodules: 'true'
+    - name: Clone sView Tree
+      if: steps.cache.outputs.cache-hit != 'true'
+      uses: actions/checkout@v6
+      with:
+        path: sview.git
+        fetch-depth: 1
     - name: Configure project
       if: steps.cache.outputs.cache-hit != 'true'
       env:
@@ -49,8 +55,11 @@ jobs:
           set(JPEGXL_ENABLE_PLUGINS   OFF CACHE BOOL "")
           set(JPEGXL_ENABLE_TOOLS     OFF CACHE BOOL "")
           set(JPEGXL_ENABLE_DEVTOOLS  OFF CACHE BOOL "")
+          set(JPEGXL_ENABLE_SJPEG     OFF CACHE BOOL "")
+          set(JPEGXL_ENABLE_OPENEXR   OFF CACHE BOOL "")
           set(JPEGXL_TEST_TOOLS       OFF CACHE BOOL "")
           set(BUILD_TESTING           OFF CACHE BOOL "")
+          set(BUILD_SHARED_LIBS       OFF CACHE BOOL "")
           ${{ env.TOOLCHAIN_TEXT }}
           set(CMAKE_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_DIR}/libjxl-install" CACHE PATH "")
       run: |
@@ -65,9 +74,15 @@ jobs:
       if: steps.cache.outputs.cache-hit != 'true'
       run: |
         cmake --install ./libjxl-make --prefix ./libjxl-install
-        cp -f "./libjxl.git/LICENSE"   "./libjxl-install/"
-        cp -f "./libjxl.git/README.md" "./libjxl-install/"
-        otool -l "./libjxl-install/lib/libjxl.dylib"
+    - name: Post install
+      if: steps.cache.outputs.cache-hit != 'true'
+      run: |
+        cp -f ./libjxl.git/LICENSE   ./libjxl-install/
+        cp -f ./libjxl.git/README.md ./libjxl-install/
+        # check shared library
+        #otool -l ./libjxl-install/lib/libjxl.dylib
+        # fix broken dependencies for static build (marked as 'private')
+        patch -d ./libjxl-install/lib -s -p0 < ./sview.git/3rdparty/FFmpeg/libjxl-static/libjxl-pkgconfig-static-clang.patch
     - name: Pack install
       run: |
         pushd ./libjxl-install
@@ -216,16 +231,13 @@ jobs:
         cmake --install ./openjpeg-make --prefix ./openjpeg-install
     - name: Configure FFmpeg
       if: steps.cache.outputs.cache-hit != 'true'
+      id: configure
       run: |
-        # --enable-libopenjpeg
         export PKG_CONFIG_LIBDIR=
         export PKG_CONFIG_PATH=$PWD/dav1d-install/lib/pkgconfig:$PWD/openjpeg-install/lib/pkgconfig:$PWD/libjxl-install/lib/pkgconfig:$PWD/mbedtls-install/lib/pkgconfig
-        aBuildRoot=$PWD
-        # redirect error state from tee
         set -o pipefail
         pushd ./ffmpeg.git
-        ./configure \
-          --prefix="$aBuildRoot/ffmpeg-install" \
+        if ./configure \
           --disable-debug --disable-stripping \
           --disable-doc \
           --extra-version=sView.ru \
@@ -236,11 +248,30 @@ jobs:
           --enable-runtime-cpudetect \
           --enable-libdav1d --enable-libjxl --enable-libopenjpeg \
           --disable-audiotoolbox \
+          --install-name-dir="@executable_path/../Frameworks" \
           --extra-cflags="-mmacosx-version-min=$MACOSX_DEPLOYMENT_TARGET -arch arm64" \
           --extra-ldflags="-mmacosx-version-min=$MACOSX_DEPLOYMENT_TARGET" \
-          --install-name-dir="@executable_path/../Frameworks" \
-          2>&1 | tee ../ffmpeg-config.log
+            2>&1 | tee ../ffmpeg-config.log; then
+          echo "status=true" >> $GITHUB_OUTPUT
+        else
+          echo "status=false" >> $GITHUB_OUTPUT
+        fi
         popd
+    - name: Upload FFmpeg configure log
+      if: steps.cache.outputs.cache-hit != 'true'
+      uses: actions/upload-artifact@v4
+      with:
+        name: ffmpeg-${{ env.SYSTEM }}-${{ env.ARCH }}-config.log
+        path: ffmpeg.git/ffbuild/config.log
+        if-no-files-found: error
+        retention-days: 1
+    - name: Check FFmpeg configure status
+      if: steps.cache.outputs.cache-hit != 'true'
+      run: |
+        if [ "${{ steps.configure.outputs.status }}" != "true" ]; then
+          echo "Error: configuration failed, check logs"
+          exit 1
+        fi
     - name: Build FFmpeg
       if: steps.cache.outputs.cache-hit != 'true'
       run: |
@@ -251,12 +282,15 @@ jobs:
     - name: Install FFmpeg
       if: steps.cache.outputs.cache-hit != 'true'
       run: |
+        export DESTDIR="$PWD/ffmpeg-install-tmp"
         pushd ./ffmpeg.git
         make install
         popd
-    - name: Post-install FFmpeg
+    - name: Post Install FFmpeg
       if: steps.cache.outputs.cache-hit != 'true'
       run: |
+        mkdir -p ./ffmpeg-install
+        mv ./ffmpeg-install-tmp/usr/local/* ./ffmpeg-install/
         ls -la ./ffmpeg-install/lib/
         cp -f ./ffmpeg-config.log           ./ffmpeg-install/
         cp -f ./ffmpeg.git/Changelog        ./ffmpeg-install/
@@ -265,9 +299,8 @@ jobs:
         cp -f ./ffmpeg.git/COPYING.LGPLv2.1 ./ffmpeg-install/
         cp -f ./ffmpeg.git/COPYING.LGPLv3   ./ffmpeg-install/
         # copy dependencies
-        cp -f -P ./libjxl-install/lib/*.dylib ./ffmpeg-install/lib/
+        #cp -f -P ./libjxl-install/lib/*.dylib ./ffmpeg-install/lib/
         otool -l "./ffmpeg-install/bin/ffmpeg"
-        #otool -l "./ffmpeg-install/lib/libavcodec.dylib"
         DYLD_LIBRARY_PATH=$PWD/ffmpeg-install/lib ./ffmpeg-install/bin/ffmpeg -version
     - name: Pack install
       run: |
diff --git a/.github/workflows/build_sview_mingw_ffmpeg.yml b/.github/workflows/build_sview_mingw_ffmpeg.yml
--- a/.github/workflows/build_sview_mingw_ffmpeg.yml
+++ b/.github/workflows/build_sview_mingw_ffmpeg.yml
@@ -20,7 +20,7 @@ env:
   OPENJPEG_REF: 'v2.5.4'
   DAV1_REF:     '1.5.3'
   LIBJXL_REF:   'v0.11.1'
-  CACHE_REV:    'cache3'
+  CACHE_REV:    'cache5'
 
 jobs:
   build-libjxl:
@@ -40,6 +40,12 @@ jobs:
         ref: ${{ env.LIBJXL_REF }}
         fetch-depth: 1
         submodules: 'true'
+    - name: Clone sView Tree
+      if: steps.cache.outputs.cache-hit != 'true'
+      uses: actions/checkout@v6
+      with:
+        path: sview.git
+        fetch-depth: 1
     - name: Install Dependencies
       if: steps.cache.outputs.cache-hit != 'true'
       run: |
@@ -64,6 +70,7 @@ jobs:
           set(JPEGXL_ENABLE_DEVTOOLS  OFF CACHE BOOL "")
           set(JPEGXL_TEST_TOOLS       OFF CACHE BOOL "")
           set(BUILD_TESTING           OFF CACHE BOOL "")
+          set(BUILD_SHARED_LIBS       OFF CACHE BOOL "")
           ${{ env.TOOLCHAIN_TEXT }}
           set(CMAKE_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_DIR}/libjxl-install" CACHE PATH "")
       run: |
@@ -77,12 +84,17 @@ jobs:
       if: steps.cache.outputs.cache-hit != 'true'
       run: |
         cmake --install ./libjxl-make --prefix ./libjxl-install
+    - name: Post install
+      if: steps.cache.outputs.cache-hit != 'true'
+      run: |
         cp -f "./libjxl.git/LICENSE"   "./libjxl-install/"
         cp -f "./libjxl.git/README.md" "./libjxl-install/"
         cp -f /usr/${TOOLCHAIN_PREFIX}/lib/libwinpthread-1.dll             ./libjxl-install/bin/
         cp -f /usr/lib/gcc/${TOOLCHAIN_PREFIX}/13-posix/libstdc++-6.dll    ./libjxl-install/bin/
         cp -f /usr/lib/gcc/${TOOLCHAIN_PREFIX}/13-posix/libgcc_s_seh-1.dll ./libjxl-install/bin/
         /usr/${TOOLCHAIN_PREFIX}/bin/strip ./libjxl-install/bin/libstdc++-6.dll --strip-unneeded
+        # fix broken dependencies for static build (marked as 'private')
+        patch -d ./libjxl-install/lib -s -p0 < ./sview.git/3rdparty/FFmpeg/libjxl-static/libjxl-pkgconfig-static-gcc.patch
     - name: Upload build
       uses: actions/upload-artifact@v4
       with:
@@ -223,19 +235,15 @@ jobs:
         cmake --install ./openjpeg-make --prefix ./openjpeg-install
     - name: Configure FFmpeg
       if: steps.cache.outputs.cache-hit != 'true'
+      id: configure
       run: |
         export PKG_CONFIG_LIBDIR=
         export PKG_CONFIG_PATH=/usr/${TOOLCHAIN_PREFIX}/lib/pkgconfig:$PWD/dav1d-install/lib/pkgconfig:$PWD/openjpeg-install/lib/pkgconfig:$PWD/libjxl-install/lib/pkgconfig
-        anFFmpegInstall=$PWD/ffmpeg-install
-        # redirect error state from tee
         set -o pipefail
         pushd ./ffmpeg.git
         # --enable-hardcoded-tables - build fails on 8.0.1
-        # --enable-libdav1d --enable-libopenjpeg --enable-gpl --enable-avisynth
-        ./configure \
-          --prefix=$anFFmpegInstall \
-          --enable-cross-compile --target-os=mingw32 --cross-prefix=${TOOLCHAIN_PREFIX}- --arch=x86_64 \
-          --extra-ldflags=-static-libgcc \
+        # --enable-gpl --enable-avisynth
+        if ./configure \
           --disable-debug --disable-stripping \
           --disable-doc \
           --extra-version=sView.ru \
@@ -245,8 +253,29 @@ jobs:
           --enable-pthreads --disable-w32threads \
           --enable-runtime-cpudetect \
           --enable-libdav1d --enable-libopenjpeg --enable-libjxl \
-          2>&1 | tee ../ffmpeg-config.log
+          --enable-cross-compile --target-os=mingw32 --cross-prefix=${TOOLCHAIN_PREFIX}- --arch=x86_64 \
+          --extra-ldflags="-static-libgcc" \
+            2>&1 | tee ../ffmpeg-config.log; then
+          echo "status=true" >> $GITHUB_OUTPUT
+        else
+          echo "status=false" >> $GITHUB_OUTPUT
+        fi
         popd
+    - name: Upload FFmpeg configure log
+      if: steps.cache.outputs.cache-hit != 'true'
+      uses: actions/upload-artifact@v4
+      with:
+        name: ffmpeg-${{ env.SYSTEM }}-${{ env.ARCH }}-config.log
+        path: ffmpeg.git/ffbuild/config.log
+        if-no-files-found: error
+        retention-days: 1
+    - name: Check FFmpeg configure status
+      if: steps.cache.outputs.cache-hit != 'true'
+      run: |
+        if [ "${{ steps.configure.outputs.status }}" != "true" ]; then
+          echo "Error: configuration failed, check logs"
+          exit 1
+        fi
     - name: Build FFmpeg
       if: steps.cache.outputs.cache-hit != 'true'
       run: |
@@ -257,9 +286,15 @@ jobs:
     - name: Install FFmpeg
       if: steps.cache.outputs.cache-hit != 'true'
       run: |
+        export DESTDIR="$PWD/ffmpeg-install-tmp"
         pushd ./ffmpeg.git
         make install
         popd
+    - name: Post Install FFmpeg
+      if: steps.cache.outputs.cache-hit != 'true'
+      run: |
+        mkdir -p ./ffmpeg-install
+        mv ./ffmpeg-install-tmp/usr/local/* ./ffmpeg-install/
         cp -f ./ffmpeg-config.log           ./ffmpeg-install/
         cp -f ./ffmpeg.git/Changelog        ./ffmpeg-install/
         cp -f ./ffmpeg.git/README.md        ./ffmpeg-install/
